### ISSUE TITLE
will it supports folkes new lazy?

### ISSUE THREAD

**Issue by luxus** [aileot/nvim-laurel#155]
hi aileot,
https://github.com/folke/lazy.nvim
would be lovely. 

you done a huge job :)
that's a lot of macros.
are you working on a big new config?

**Comment by aileot** [comment]
Thank you for the kind comment :)

To use macros before registering it with plugin manager, we have to add the root paths of macros to 'runtimepath' manually.

It is common to do that when we write our config on some features of such plugins as runtime compiler, macros, any other Lua/Vimscript functions, or plugin manager itself.

In most cases, plugin manager should only manage the versions for such plugins.

Thus, lazy.nvim can support nvim-laurel on version control, but we need another script to make sure nvim-laurel macros are ready in 'runtimepath' before. For example,

```lua
-- In init.lua or somewhere else

local function prerequisites(name, url)
  -- To manage the version of repo, the path should be where your plugin manager will download it.
  -- In this example, I use lazy.nvim because it specifies its default download path and it manages plugins without 'packpath'.
  -- Adjust `dir` if you prefer another plugin manager.
	local dir = vim.fn.stdpath("data") .. "/lazy"
	local path = dir .. "/" .. name
	if not vim.loop.fs_stat(path) then
		vim.fn.system({
			"git",
			"clone",
			"--filter=blob:none",
			"--single-branch",
			url,
			path,
		})
	end
	vim.opt.runtimepath:prepend(path)
end

-- Install your favorite plugin manager.
prerequisites("lazy.nvim", "https://github.com/folke/lazy.nvim")
-- prerequisites("packer.nvim", "https://github.com/wbthomason/packer.nvim")
-- prerequisites("dein.vim", "https://github.com/Shougo/dein.vim")

-- Install macros like nvim-laurel
prerequisites("nvim-laurel", "https://github.com/aileot/nvim-laurel")

-- Install a runtime compiler if you feel like
prerequisites("hotpot.nvim", "https://github.com/rktjmp/hotpot.nvim")

require("hotpot").setup({
	compiler = {
		macros = {
			env = "_COMPILER",
			allowedGlobals = false,
		},
	},
})

require("load-plugins-by-lazy")
```

```fennel
;; In ~/.config/fnl/load-plugins-by-lazy.fnl

(local lazy (require :lazy))
(local opts {:defaults {:lazy true}})

;; Just manage their versions
(lazy.setup [:rktjmp/hotpot.nvim
             :aileot/nvim-laurel
             ...]
            opts)
```

P.S. I have updated [nvim-fnl](https://github.com/aileot/nvim-fnl), a part of my private dotfiles. I hope it can be of some help to you ;)

**Comment by luxus** [comment]
<img width="350" alt="Screenshot 2022-12-21 at 15 23 10" src="https://user-images.githubusercontent.com/7449/208927467-a6a78875-a128-448d-811a-d2163f3ca59f.png">
is this right? have you tried it?

**Comment by aileot** [comment]
Yes, you are right. The path was wrong. I fixed the path in the snippet above.
I mean it as a sample local module to manage plugins with lazy.nvim in Fennel.

**Comment by luxus** [comment]
Ah, okay, my bad; I thought this was a working example; I think I was too tired to realize this.
my fennel game is still very weak, I tried to make it work and failed. I will take a look on it tomorrow after some sleep. :D

**Comment by luxus** [comment]
okay, i think i need to wait until you have time for more instructions.
i forked your config and tried.
https://github.com/luxus/nvim-fnl

thanks for all your answers so far, keep up the good work. and maybe post it on [reddit](https://www.reddit.com/r/neovim/) if you want some traction

**Comment by aileot** [comment]
I have to say `...` in the snippets represents just ellipsis, not varargs (Variadic Arguments). You should simply remove it or replace it with other plugins like `:folke/tokyonight.nvim`.

**Comment by luxus** [comment]
great :D haha i thought that the ... is some fennel magic its working now .. wonderful
